Ch 70 fixes
deathworlders/online pull request #125
Opened 2020-10-01 14:38 UTC by isotopp

Minor Typo

Big fix "Wild"-> "Wilde" through first half of chapter.

2020-10-01 14:38 UTC, isotopp commented
Two separate commits for your convenience.

2020-10-11 21:30 UTC, ctwelve requested changes
Thanks for the work! I can't accept the PR however; Wild vs Wilde is a deliberate style choice, where non-English speakers will tend to use Wild as a phonetic substitution. Also...it's an accurate description of Wilde's perspective :D

2020-10-23 08:10 UTC, isotopp commented
Wild->Wilde reverted.

2020-11-06 21:44 UTC, ctwelve approved these changes

2020-11-06 21:45 UTC, merged