Chapters 21 - 23
deathworlders/online pull request #68
Opened 2018-06-04 10:05 UTC by CodeWarrior-Hawaii

OK, this is a big 'un.  I had forgotten that Chapter 22 was 42 million words long.  I have commits broken in to Punctuation, Callsigns, and Re-Linerating (undoing the forced word-wrapping).

Let me know what I missed because I am sure that I missed or screwed up something in this gigantic "Chapter".

2018-06-05 19:00 UTC, ctwelve commented
Oh Goddamn this is a biggie!

2018-06-05 19:02 UTC, ctwelve requested changes
Hello. In the datelines you've deleted all trailing space. This is incorrect, because the (at least) two extra spaces after the dateline tell Markdown to do a linebreak without a new paragraph. Basically works like `<br>` does in HTML.

Please put them back, because @HamboneHFY considers the stacked datelines essential to the presentation.

2018-06-05 19:10 UTC, ctwelve requested changes
Metadata! Also I note the ellipsis character has appeared; we don't want it! Please replace with three periods everywhere.

2018-06-05 19:10 UTC, ctwelve commented on content/books/deathworlders/chapter-22-warhorse-pt1-first-year.md
> +--- title: "Chapter 22: Warhorse Part 1—The First Year" date: 2015-09-18 aliases:   - /book/deathworlders/chapter-22-warhorse ---
The metadata block is...pretty thoroughly broken, in all the files. It's a YAML front matter block encased in three dashes. It has to be formatted **precisely**  and will not tolerate this.

2018-06-05 19:10 UTC, ctwelve commented on content/books/deathworlders/chapter-22-warhorse-pt2-second-year.md
> +--- title: "Chapter 22: Warhorse Part 2—The Second Year" date: 2015-09-19 aliases:   - /book/deathworlders/chapter-22-warhorse/second-year ---
Same deal here. Broken metadata! And...so on through all the files.

2018-06-06 06:24 UTC, CodeWarrior-Hawaii commented
Alright.  Ellipsis character burninated with extreme prejudice.  Chapter metadata blocks fixed.  Spaces reverted to section headers.  Also some spelling and punctuation fixes.

2018-06-08 21:41 UTC, ctwelve approved these changes
Looks good!

2018-06-08 21:47 UTC, merged